(()=>{'use strict';
const pads=[...document.querySelectorAll('.pad')],statusEl=document.querySelector('#status'),selectedName=document.querySelector('#selectedName'),readout=document.querySelector('#readout'),mainWave=document.querySelector('#mainWave'),waveTouch=document.querySelector('#waveTouch'),playhead=document.querySelector('#playhead'),micButton=document.querySelector('#micButton'),deleteBtn=document.querySelector('#deleteMode'),resetBtn=document.querySelector('#resetEdit');
let ctx=null,micStream=null,rec=null,chunks=[],recording=-1,timer=null,liveRAF=0,selected=0,delMode=false,headRAF=0,scratchWorklet=null;
const pointers=new Map();
const d=Array.from({length:4},()=>({blob:null,buffer:null,wave:null,source:null,gain:null,playing:false,pitch:0,tempPitch:0,tempSpeed:1,scratch:null}));
const status=t=>statusEl.textContent=t;
async function audio(){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')await ctx.resume()}
async function mic(){try{await audio();if(!navigator.mediaDevices?.getUserMedia)throw 0;if(!micStream)micStream=await navigator.mediaDevices.getUserMedia({audio:true});micButton.classList.add('active');micButton.textContent='● MICRÓFONO ACTIVO';status('MICRÓFONO LISTO · tocá un pad vacío')}catch(e){status('NO SE PUDO ACTIVAR EL MICRÓFONO · revisá el permiso')}}
function drawWave(canvas,a,active=false){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#0b0b0a';c.fillRect(0,0,w,h);if(!a)return;c.strokeStyle=active?'#ffe16b':'#f5c400';c.lineWidth=1.5;c.beginPath();const st=Math.max(1,Math.floor(a.length/w));for(let x=0;x<w;x++){let s=x*st,e=Math.min(a.length,s+st),p=0;for(let j=s;j<e;j++)p=Math.max(p,Math.abs(a[j]));const y=h/2-p*h*.43;x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.strokeStyle='#ffffff18';c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke()}
function liveWave(i,an){if(recording!==i)return;const cv=pads[i].querySelector('.mini-wave'),c=cv.getContext('2d'),w=cv.width,h=cv.height,a=new Float32Array(an.fftSize);an.getFloatTimeDomainData(a);c.clearRect(0,0,w,h);c.fillStyle='#0b0b0a';c.fillRect(0,0,w,h);c.strokeStyle='#ff5548';c.lineWidth=2;c.beginPath();for(let x=0;x<w;x++){const y=h/2-a[Math.floor(x/w*a.length)]*h*.43;x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();liveRAF=requestAnimationFrame(()=>liveWave(i,an))}
function makeWave(buf,n=1800){const ch=buf.getChannelData(0),o=new Float32Array(Math.min(n,ch.length)),b=ch.length/o.length;for(let i=0;i<o.length;i++){let s=i*b,e=(i+1)*b,p=0;for(let j=s|0;j<e&&j<ch.length;j++)p=Math.max(p,Math.abs(ch[j]));o[i]=p}return o}
function setPos(p){p=Math.max(0,Math.min(1,p));playhead.style.left=(p*100)+'%';return p}
function updateRead(p=0){const x=d[selected];readout.textContent=`PITCH ${x.pitch+x.tempPitch>=0?'+':''}${x.pitch+x.tempPitch} · SPEED ${x.tempSpeed.toFixed(2)}× · POS ${Math.round(p*100)}%`}
function redraw(){d.forEach((x,i)=>{pads[i].querySelector('.pad-label').textContent=x.buffer?x.buffer.duration.toFixed(2)+'s':'EMPTY';if(recording!==i)drawWave(pads[i].querySelector('.mini-wave'),x.wave,i===selected)});const x=d[selected];selectedName.textContent=`PAD ${String(selected+1).padStart(2,'0')} · ${x.buffer?x.buffer.duration.toFixed(2)+' SEC':'SIN AUDIO'}`;drawWave(mainWave,x.wave,true);setPos(0);updateRead()}
function stopPad(i){const x=d[i];if(x.source){try{x.source.stop()}catch(e){}try{x.source.disconnect()}catch(e){}}if(x.gain)try{x.gain.disconnect()}catch(e){}x.source=x.gain=null;x.playing=false;x.tempPitch=0;x.tempSpeed=1;pads[i].classList.remove('playing');if(i===selected)updateRead()}
function applyPad(i){const x=d[i];if(!x.source)return;x.source.playbackRate.setTargetAtTime(Math.max(.5,Math.min(2,x.tempSpeed)),ctx.currentTime,.012);x.source.detune.setTargetAtTime((x.pitch+x.tempPitch)*100,ctx.currentTime,.012)}
async function playPad(i){const x=d[i];if(!x.buffer)return;await audio();stopPad(i);const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=x.buffer;s.loop=true;s.connect(g).connect(ctx.destination);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.linearRampToValueAtTime(1,ctx.currentTime+.012);x.source=s;x.gain=g;x.playing=true;x.tempPitch=0;x.tempSpeed=1;applyPad(i);s.start();pads[i].classList.add('playing');setPos(0)}
function releasePad(i){const x=d[i];if(!x.source||!x.gain)return;const t=ctx.currentTime;x.gain.gain.cancelScheduledValues(t);x.gain.gain.setValueAtTime(Math.max(.0001,x.gain.gain.value),t);x.gain.gain.linearRampToValueAtTime(.0001,t+.5);try{x.source.stop(t+.51)}catch(e){}}
async function recordPad(i){if(recording>=0||d[i].buffer)return;if(!micStream){await mic();if(!micStream)return}await audio();recording=i;pads[i].classList.add('recording');status(`PAD ${String(i+1).padStart(2,'0')} · PREPARANDO · grabación en 1 segundo`);const src=ctx.createMediaStreamSource(micStream),an=ctx.createAnalyser();an.fftSize=2048;src.connect(an);d[i].an=an;timer=setTimeout(()=>{if(recording!==i)return;chunks=[];rec=new MediaRecorder(micStream);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=finishRecording;rec.start();status(`GRABANDO PAD ${String(i+1).padStart(2,'0')} · soltá para terminar`);liveWave(i,an)},1000)}
async function finishRecording(){const i=recording;if(i<0)return;cancelAnimationFrame(liveRAF);try{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'}),ab=await blob.arrayBuffer(),buf=await ctx.decodeAudioData(ab);d[i].blob=blob;d[i].buffer=buf;d[i].wave=makeWave(buf);d[i].pitch=0;d[i].tempPitch=0;d[i].tempSpeed=1;selected=i;drawWave(pads[i].querySelector('.mini-wave'),d[i].wave,true);redraw();status(`PAD ${String(i+1).padStart(2,'0')} GRABADO · waveform completa lista`)}catch(e){status('NO SE PUDO LEER LA GRABACIÓN')}pads[i].classList.remove('recording');recording=-1;rec=null}
function stopRecording(){if(timer){clearTimeout(timer);timer=null}if(recording<0)return;const i=recording;if(rec&&rec.state!=='inactive')rec.stop();else{pads[i].classList.remove('recording');recording=-1;status('GRABACIÓN CANCELADA · soltaste antes del inicio')}}
function erase(i){stopPad(i);stopScratch(i);d[i]={blob:null,buffer:null,wave:null,source:null,gain:null,playing:false,pitch:0,tempPitch:0,tempSpeed:1,scratch:null};selected=i;redraw();delMode=false;deleteBtn.classList.remove('active');status(`PAD ${String(i+1).padStart(2,'0')} BORRADO`)}

pads.forEach((p,i)=>{p.addEventListener('pointerdown',async e=>{e.preventDefault();p.setPointerCapture(e.pointerId);selected=i;redraw();if(delMode){erase(i);return}pointers.set(e.pointerId,{mode:d[i].buffer?'play':'record',i,sx:e.clientX,sy:e.clientY,moved:false});if(d[i].buffer)await playPad(i);else await recordPad(i)});p.addEventListener('pointermove',e=>{const q=pointers.get(e.pointerId);if(!q||q.mode!=='play'||!d[q.i].source)return;const dx=e.clientX-q.sx,dy=e.clientY-q.sy;if(Math.hypot(dx,dy)<30)return;q.moved=true;const x=d[q.i];if(Math.abs(dy)>Math.abs(dx)){x.tempPitch=Math.max(-12,Math.min(12,Math.round(-dy/30)));x.tempSpeed=1}else{x.tempPitch=0;x.tempSpeed=Math.max(.5,Math.min(2,1+dx/260))}applyPad(q.i);updateRead()});p.addEventListener('pointerup',e=>{const q=pointers.get(e.pointerId);if(q?.mode==='record')stopRecording();if(q?.mode==='play')releasePad(i);pointers.delete(e.pointerId)});p.addEventListener('pointercancel',e=>{const q=pointers.get(e.pointerId);if(q?.mode==='record')stopRecording();if(q?.mode==='play')releasePad(i);pointers.delete(e.pointerId)})});

async function ensureScratchWorklet(){if(scratchWorklet)return;scratchWorklet=URL.createObjectURL(new Blob([`class TongaScratch extends AudioWorkletProcessor{constructor(){super();this.samples=null;this.pos=0;this.targetPos=0;this.speed=0;this.targetSpeed=0;this.pitch=1;this.port.onmessage=e=>{const m=e.data;if(m.type==='buffer'){this.samples=new Float32Array(m.samples);this.pos=m.pos||0;this.targetPos=this.pos}if(m.type==='state'){this.targetPos=m.pos;this.targetSpeed=m.speed;this.pitch=m.pitch}if(m.type==='stop'){this.targetSpeed=0}}}process(i,o){const out=o[0];if(!out||!this.samples)return true;const L=out[0],R=out[1];const n=this.samples.length;for(let k=0;k<L.length;k++){this.speed+=(this.targetSpeed-this.speed)*0.18;this.pos+=(this.targetPos-this.pos)*0.12;let p=this.pos;if(p<0)p+=n;if(p>=n)p-=n;let a=p|0,b=a+1;if(b>=n)b=0;let f=p-a,v=this.samples[a]*(1-f)+this.samples[b]*f;L[k]=v;if(R)R[k]=v;this.pos+=this.speed*this.pitch;if(this.pos<0)this.pos+=n;if(this.pos>=n)this.pos-=n}return true}}registerProcessor('tonga-scratch',TongaScratch);`],{type:'application/javascript'}));await ctx.audioWorklet.addModule(scratchWorklet)}
function stopScratch(i){const x=d[i];if(!x.scratch)return;try{x.scratch.node.port.postMessage({type:'stop'})}catch(e){}try{x.scratch.node.disconnect()}catch(e){}try{x.scratch.gain.disconnect()}catch(e){}x.scratch=null;cancelAnimationFrame(headRAF)}
async function startScratch(i,p){const x=d[i];if(!x.buffer)return null;await ensureScratchWorklet();stopScratch(i);const node=new AudioWorkletNode(ctx,'tonga-scratch',{outputChannelCount:[2]}),gain=ctx.createGain();gain.gain.value=.9;node.connect(gain).connect(ctx.destination);const samples=x.buffer.getChannelData(0);const copy=new Float32Array(samples);node.port.postMessage({type:'buffer',samples:copy.buffer,pos:p*samples.length},[copy.buffer]);x.scratch={node,gain,pos:p,speed:0,pitch:Math.pow(2,x.pitch/12)};return x.scratch}
function scratchHead(){cancelAnimationFrame(headRAF);const tick=()=>{const x=d[selected],s=x.scratch;if(s&&x.buffer){const p=Math.max(0,Math.min(1,s.pos));setPos(p);updateRead(p);headRAF=requestAnimationFrame(tick)}};tick()}
waveTouch.addEventListener('pointerdown',async e=>{if(!d[selected].buffer)return;e.preventDefault();waveTouch.setPointerCapture(e.pointerId);await audio();const r=waveTouch.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),s=await startScratch(selected,p);if(!s)return;s.pos=p;scratchHead();pointers.set(e.pointerId,{mode:'scratch',sx:e.clientX,sy:e.clientY,lx:e.clientX,ly:e.clientY,last:performance.now(),axis:null,moved:false});status('SCRATCH · arrastrá horizontalmente')});
waveTouch.addEventListener('pointermove',e=>{const q=pointers.get(e.pointerId);if(!q||q.mode!=='scratch')return;const x=d[selected],s=x.scratch;if(!s)return;const dx=e.clientX-q.sx,dy=e.clientY-q.sy,dist=Math.hypot(dx,dy);if(!q.axis){if(dist<30)return;q.axis=Math.abs(dx)>=Math.abs(dy)?'x':'y'}const r=waveTouch.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));if(q.axis==='y'){x.pitch=Math.max(-24,Math.min(24,Math.round(-dy/30)));s.pitch=Math.pow(2,x.pitch/12);updateRead(p);status(`PITCH PERMANENTE ${x.pitch>=0?'+':''}${x.pitch}`)}else{const now=performance.now(),dt=Math.max(8,now-q.last),dxStep=e.clientX-q.lx;const normalizedPerSec=(dxStep/r.width)/(dt/1000);const speed=Math.max(-4,Math.min(4,normalizedPerSec));s.node.port.postMessage({type:'state',pos:p*x.buffer.length,speed,pitch:Math.pow(2,x.pitch/12)});s.pos=p;updateRead(p);status(speed<0?'SCRATCH ← REVERSA':`SCRATCH → ${speed.toFixed(2)}×`);q.last=now;q.lx=e.clientX;q.ly=e.clientY}});
function endScratch(e){const q=pointers.get(e.pointerId);if(q?.mode==='scratch'){const x=d[selected];if(x.scratch){x.scratch.node.port.postMessage({type:'stop'});setTimeout(()=>{if(x.scratch)stopScratch(selected)},140)}status('SCRATCH PAUSADO')}pointers.delete(e.pointerId)}
waveTouch.addEventListener('pointerup',endScratch);waveTouch.addEventListener('pointercancel',endScratch);
deleteBtn.addEventListener('click',()=>{delMode=!delMode;deleteBtn.classList.toggle('active',delMode);status(delMode?'MODO BORRAR · tocá el pad que querés eliminar':'MODO BORRAR CANCELADO')});resetBtn.addEventListener('click',()=>{d[selected].pitch=0;if(d[selected].scratch)d[selected].scratch.pitch=1;redraw();status('PITCH PERMANENTE RESTAURADO')});micButton.addEventListener('click',mic);redraw();
})();
